### ISSUE TITLE
Manifiesto landing page outdated

### ISSUE THREAD

**Issue by sepu85** [aragon/website#102]
in the [Manifiesto webpage](https://blog.aragon.org/the-aragon-manifesto-4a21212eac03/), there's still a reference about the Aragon Foundation, wich has been replaced by the AA already.

Also, in that Foundation section, there are a couple of links: https://aragon.one/foundation/ & https://aragon.one/network that lead to blank pages.

**Comment by john-light** [comment]
Thank you for reporting @sepu85!  

The canonical version of the manifesto now lives at https://github.com/aragon/AGPs/blob/master/AGPs/AGP-0.md

In any case, the Manifesto blog post has since been updated.
