### ISSUE TITLE
Nicer "not found" page

### ISSUE THREAD

**Issue by john-light** [aragon/website#109]
I think we could have a nicer "not found" page, with a help path to get back to the previous page (so the user doesn't have to click the back button in their browser).

```
Not Found

Sorry, the page you are looking for isn't here!

[Go back] [Home page]
```

Current page:

![Screenshot_2019-10-01 Aragon(3)](https://user-images.githubusercontent.com/9424721/65963470-16f7b480-e45b-11e9-8716-747ca402fc6e.png)

**Comment by owisixseven** [comment]
To be aligned and consistent with the product:

<img width="1439" alt="Captura de pantalla 2019-10-03 a las 10 22 48" src="https://user-images.githubusercontent.com/43449463/66110872-f436de80-e5c7-11e9-93d9-cfd8aebaa04e.png">

@delfipolito this artboard is on [the landing project on Figma](https://www.figma.com/file/SuleuupZMJrCFFFhQGRscNzK/New-landing?node-id=1184%3A265)
