### ISSUE TITLE
Apply `min-height` on some topic headers to avoid misalignment

### ISSUE THREAD

**Issue by sohkai** [aragon/website#15]
<img width="996" alt="screen shot 2017-11-28 at 11 22 32 am" src="https://user-images.githubusercontent.com/4166642/33331133-c63ea94c-d42e-11e7-8cd7-80a2f5f58665.png">

It might be nice if the headers were the same size so the subtext doesn't seem misaligned with each other.

**Comment by luisivan** [comment]
Closing since we released a totally new version of the website
