### ISSUE TITLE
Mention Foundation's legal name in /foundation

### ISSUE THREAD

**Issue by izqui** [aragon/website#16]
We refer to the 'Aragon Foundation' but that's an entity that doesn't exist. We should mention the name of the legal entity, its address and its current governance structure.

I would also highlight how we envision the Foundation to slowly transition most of its power to the Aragon Network DAO. We did a blog post that explains this in detail: https://blog.aragon.one/the-path-to-mainstream-decentralized-organizations-d95a89d3cac4

PS: should we add any copyright notices on the footer? @mariapao

**Comment by john-light** [comment]
The Aragon Association is mentioned by name on the project page now:

https://aragon.org/project

We can probably close this issue now.
