### ISSUE TITLE
Copy suggestions for /core

### ISSUE THREAD

**Issue by sohkai** [aragon/website#17]
## In Accounting:

> Unprecedented level of transparency can be gained through the use of a public blockchain to engrave every entry permanently on the ledger

Might sound better as "An unprecedented" or "Unprecedented levels".

It might also be nice to reword so that "ledger" is given more context (right now it's unclear what this "ledger" is). An example:

> An unprecedented level of transparency can be gained through the use of a public blockchain as an immutable ledger that permanently engraves every entry

-----------

## In Permissions:

> Fine-grained permissions deliver the freedom to create an organization that ~~will~~ work**s** for you

#### Consider rewording:
> Permissions can be granular and assigned in fine detail. You can choose to give people a certain degree of control over the organization and the privileges can be escalated easily if the person isn't allowed to perform a desired action

to

> Permissions can be granular and assigned in fine detail. ~~You can choose to give people a certain degree of control over the organization and the privileges can be escalated easily if the person isn't allowed to perform a desired action~~ **You choose the degree of control someone has over an organization, with paths of privilege escalation available for actions outside of their control**

(without patches)

> Permissions can be granular and assigned in fine detail. You choose the degree of control someone has over an organization, with paths of privilege escalation available for actions outside of their control

#### Consider rewording: 
> By assigning different permissions to people, you can create the kind of organizational structure that is best suited for your needs

to 

> ~~By assigning~~ **Aragon allows you to assign** different permissions to people, **so** you can create the ~~kind of~~ organizational structure that ~~is best suited~~ **best suits** your needs

(without the patches)
> Aragon allows you to assign different permissions to people, so you can create the organizational structure that best suits your needs

**Comment by onbjerg** [comment]
Just adding a quick comment here:

>Permissions can be granular and assigned in fine detail.

This sounds a bit repetitive since you could replace "in fine detail" with "granularly", so they mean the same thing.

**Comment by Smokyish** [comment]
@sohkai 
> An unprecedented level of transparency can be gained through the use of a public blockchain as an immutable ledger that permanently engraves every entry

The word immutable is still a bit controversial because of theDAO hard-fork, so trying to avoid that.

> Permissions can be granular and assigned in fine detail. You choose the degree of control someone has over an organization, with paths of privilege escalation available for actions outside of their control

Wanted to have the word "people" for consistency here as we mention it in other sections multiple times.

> Aragon allows you to assign different permissions to people, so you can create the organizational structure that best suits your needs

Using the word Aragon is inconsistent with all the other content and the paragraph is shorter which causes the text block to change

@onbjerg 
> Permissions can be assigned granularly.

That's a much shorter sentence and sounds a bit incomplete imo.
