### ISSUE TITLE
Use different icon alignment in /core subsection?

### ISSUE THREAD

**Issue by sohkai** [aragon/website#18]
<img width="1029" alt="screen shot 2017-11-28 at 11 26 17 am" src="https://user-images.githubusercontent.com/4166642/33331831-ad011f8a-d430-11e7-8553-26734dccac89.png">

It may look better if the purple icons were left, center, and right-aligned, respectively.

**Comment by sohkai** [comment]
Centering the paragraphs on larger screens seems like the best thing to do. The only other place where we have icons and text like this is in /join, which should probably be updated as well for consistency.

**Comment by luisivan** [comment]
Closing since we released a totally new version of the website
