### ISSUE TITLE
Copy suggestions in /foundation

### ISSUE THREAD

**Issue by sohkai** [aragon/website#20]
> Cornerstone for architecting the project

Reads a bit off; either missing an article ("The cornerstone") or something else?

> Heart of the early development

Also reads a bit off, I'm not sure what you mean here. Also really reminds me of "Heart of the Swarm" 😉 

> The Aragon Foundation is laying down the first bricks on the road to what will become

"What **it** will become"?

> The Aragon Foundation is a non-profit organization ~~which was~~ created to nurture the project in ~~it's~~ **its** early phases

**Comment by Smokyish** [comment]
@sohkai 
> Reads a bit off; either missing an article ("The cornerstone") or something else?

It had The originally, was removed during proof reading session.

> Also reads a bit off, I'm not sure what you mean here. Also really reminds me of "Heart of the Swarm" 😉 

Also okayed in proof reading, the idea is to give the sense that the Foundation is the heart that has given and keeps the project alive in it's early development (also plays into the picture beside the text, the Ethereum logo within another one)

> "What **it** will become"?

That would refer to the future of the Foundation, it being the Foundation, and we're talking about the future of the project in this case. We also don't know what the future holds and this should give the sense that there is a future along this road we're creating and travelling on.

> The Aragon Foundation is a non-profit organization ~~which was~~ created to nurture the project in ~~it's~~ **its** early phases

This would shorten the sentence to look less aligned with the other content and i think it's good to mention that this is the reason why it was created.
