### ISSUE TITLE
Copy suggestions in /about

### ISSUE THREAD

**Issue by sohkai** [aragon/website#21]
> Organizations **,** like companies **,** exist to create value for their owners and users. They use the resources available to them in order to provide services and ~~to~~ create products

> Evolution of the Internet and Blockchain technology are changing the ways we interact with each other

Reads a bit off; maybe just "Internet and Blockchain technologies are ..."? (Also leads to question of whether "Blockchain" is a proper noun)

> We believe that the progression**s** of modern technology ~~solutions~~ **,** such as ~~the invention of~~ the blockchain **,** are changing the incentives for people to interact with each other. ~~We~~ **Together, we** are building the tools **that empower** ~~for~~ the next generation of organizations to take advantage of this revolution

^ Some real superpower stuff here!

> ~~Trying out~~ **Experimenting with** new governance models has been a ~~very~~ risky endeavour ~~during~~ **throughout** previous iterations of society. Now, for the first time in history, we can let a thousand governance models emerge from the comfort of our laptops

**Comment by Smokyish** [comment]
@sohkai 
> Organizations **,** like companies **,** exist to create value for their owners and users. They use the resources available to them in order to provide services and ~~to~~ create products

This makes the paragraph much shorter and less aligned with the other content. Services and products can also be different things, so feel this is appropriate as is.

> Reads a bit off; maybe just "Internet and Blockchain technologies are ..."? (Also leads to question of whether "Blockchain" is a proper noun)

> We believe that the progression**s** of modern technology ~~solutions~~ **,** such as ~~the invention of~~ the blockchain **,** are changing the incentives for people to interact with each other. ~~We~~ **Together, we** are building the tools **that empower** ~~for~~ the next generation of organizations to take advantage of this revolution

This would change the number of lines in the text, now both paragraphs have four lines. And these are technological solutions to problems, blockchain technology being one invention in history, like the microprocessor, that it can have different applications, but the invention of the underlying tech is what is revolutionary. And we're building the tools that are necessary for these next gen orgs to exist and be a part of the revolution, not just empowering them, enabling them.
