### ISSUE TITLE
Icon alignment in /join

### ISSUE THREAD

**Issue by sohkai** [aragon/website#23]
<img width="1024" alt="screen shot 2017-11-28 at 1 24 39 pm" src="https://user-images.githubusercontent.com/4166642/33336991-97f905f8-d43f-11e7-9a89-1d0a349999d1.png">

It might be nice if these icons were centered with their text, or maybe even left, center, and right-aligned (if we adopt that style)?

**Comment by luisivan** [comment]
Closing since we released a totally new version of the website
