### ISSUE TITLE
Image for twitter links

### ISSUE THREAD

**Issue by izqui** [aragon/website#29]
It currently appears as an empty image, we should add the aragon logo.

<img width="518" alt="2017-11-29 at 1 45 15 pm" src="https://user-images.githubusercontent.com/447328/33375861-a601331a-d50b-11e7-90b8-730179a784f4.png">

**Comment by onbjerg** [comment]
These are the minimal meta tags for OpenGraph and Twitter (Twitter replaces OG tags with their own for you)

```html
<meta property="og:title" content="title">
<meta property="og:description" content="description">
<meta property="og:image" content="absolute path to logo">
<meta property="og:url" content="https://aragon.one">
<meta name="twitter:card" content="summary_large_image">
```
