### ISSUE TITLE
Clearer description of the product for new users on Homepage

### ISSUE THREAD

**Issue by philreader** [aragon/website#32]
First off, new UI looks great! However I'm not sure it really describes what Aragon does or how it could benefit someone who is looking at it for the first time. IMO some of this messaging feels better suited for the "About" section.

For a new user, the home screen doesn't really describe how I would use Aragon and that it would even be useful for what I want. It would be nice if the first section of the homepage could explain exactly what Aragon is and how it can be used (without the user having to scroll)

For example, 
```
"Dashboard for managing tokenholders"
Key Features:
1. Crowdfund a new decentralized venture
2. Easily enable tokenholders to vote on key issues
3. Manage funds in a transparent way

This can lead to a clear call to action, a button that says "Try it now" 
(instead of "web version" and "Aragon Core" in the corner or seeing it after three scrolls 
down.
```

All of the above should fit without the user having to scroll.

Below that, a screenshot of the application (instead of a blank internet browser) would be awesome.

Examples with nice calls to action and explanations: 
https://wistia.com/
https://stripe.com/
https://getbase.com/
I feel Aragon is such a new category of application that the key features should be explained upfront.

**Comment by luisivan** [comment]
Closing since we released a totally new version of the website

**Comment by luisivan** [comment]
By the way, what do you think of it @philreader, is it clearer now?
