### ISSUE TITLE
Add missing team members to /about

### ISSUE THREAD

**Issue by izqui** [aragon/website#36]
@john-light and @alexarwr are missing in the website.

Are the drawings for them in the works?

Anyway, this should be part of the onboarding process for new team members.

**Comment by luisivan** [comment]
Looping in @monicazng

**Comment by monicazng** [comment]
Already sent 2 pull requests to aragon-wiki

**Comment by luisivan** [comment]
Solved https://github.com/aragon/website/pull/41
