### ISSUE TITLE
Some labels are smaller than expected

### ISSUE THREAD

**Issue by luisivan** [aragon/website#38]
![screen shot 2018-01-10 at 2 12 15 am](https://user-images.githubusercontent.com/718208/34751257-c15f1440-f5ab-11e7-80a4-60209960f474.png)

Seems like some change in `aragon-ui` has triggered this. Can you help @bpierre?

**Comment by bpierre** [comment]
Fixed, I added a note on the README: https://github.com/aragon/website/commit/a60ed8f9fec9ca233699c9c1caaf58347fa213ab
