### ISSUE TITLE
Remove links to 0.3 web and desktop apps

### ISSUE THREAD

**Issue by john-light** [aragon/website#39]
Community members are reporting persistent issues with these apps and are being actively discouraged from using the apps by devs and other community members. To prevent users from going down an "unhappy path" we should remove or "grey-out" these links until the next stable release is out since that is where all developer focus is right now.

@Smokyish @luisivan @izqui

**Comment by izqui** [comment]
I agree. I encouraged never having them in the new website. It is so funny how stuff rots if you don't give enough love, this used to work almost perfectly some months ago

**Comment by luisivan** [comment]
Cool, we're weeks away from having 0.5 out so this seems reasonable

**Comment by john-light** [comment]
Thanks @izqui @luisivan. Who can make these changes? I would do it but I don't know how to edit the code to do so.

**Comment by Smokyish** [comment]
Agreed. I would add a Coming Soon with a link to [News from the Front](https://blog.aragon.one/news-from-the-front-5820cd9f2e46).

I made the changes to `aragon-ui` PreFooter, but cause i'm not too familiar with it and getting a linter error, sent it over to @bpierre to check out.

**Comment by bpierre** [comment]
Done ➡️ https://aragon.one/

I published the @Smokyish changes in PreFooter:

<img width="422" alt="image" src="https://user-images.githubusercontent.com/36158/35072163-57812e60-fbdb-11e7-8748-5cb5850a2e05.png">

And I also replaced the buttons in the header by a single one, pointing to the article:

<img width="1161" alt="image" src="https://user-images.githubusercontent.com/36158/35072141-43d72b94-fbdb-11e7-932c-da3014dfe478.png">

Please reopen if anything is missing / incorrect! 😊

**Comment by john-light** [comment]
@bpierre can you please change the `Download` link in the footer to `[Preview Aragon 0.5](https://blog.aragon.one/news-from-the-front-5820cd9f2e46)`?

**Comment by bpierre** [comment]
Done: https://aragon.one/

I also updated the “ready to try” section, from this:

<img width="1075" alt="image" src="https://user-images.githubusercontent.com/36158/35090525-d3f434b4-fc31-11e7-82f3-f9700d7697b7.png">

To this:

<img width="1113" alt="image" src="https://user-images.githubusercontent.com/36158/35090538-dfc1d4ae-fc31-11e7-9633-623ced1340ba.png">
