### ISSUE TITLE
Twitter and Medium icons wrong in the Team page

### ISSUE THREAD

**Issue by elioqoshi** [aragon/website#47]
The Twitter icon is stretched and the Medium icon is the old one from the previous medium in the About page in the team section:
https://aragon.one/about

It should be like that:
![image](https://user-images.githubusercontent.com/5436686/36533523-1765ee1a-17c4-11e8-9dcc-a6d7e6a5bffc.png)

**Comment by elioqoshi** [comment]
PR for the Medium Icon:
https://github.com/aragon/website/pull/48

**Comment by elioqoshi** [comment]
PR for the Twitter icons
https://github.com/aragon/website/pull/49

**Comment by bpierre** [comment]
Thanks for your help @elioqoshi! 💯

Now that the Medium icon has a background shape, we should probably update the others to make the icons look more balanced?

- Twitter [recommends using a background shape](https://about.twitter.com/en_us/company/brand-resources.html#social-icons) for social icons.
- GitHub doesn’t, but using the [recommended color](https://github.com/logos) would probably be enough.

@elioqoshi @jounih Thoughts?

**Comment by elioqoshi** [comment]
@bpierre Indeed! I am not sure if Medium guidelines suggest putting the monogram in a circle shape, while I'm not sure if GitHub can be put in a square shape. I suppose having them mixed wouldn't be fitting. The GitHub black should be used there, yep.

**Comment by bpierre** [comment]
@elioqoshi It’s been a while so I merged your PRs, thanks a lot for your contribution! ✨ (and sorry for the delay 😖)

@jounih @elioqoshi please reopen if you want to discuss / iterate on it.
