### ISSUE TITLE
Update hero module in home page

### ISSUE THREAD

**Issue by izqui** [aragon/website#53]
<img width="1847" alt="2018-03-30 at 11 06 04 am" src="https://user-images.githubusercontent.com/447328/38132200-5cc5531c-340a-11e8-8b71-7b71471093d8.png">

I would love for this module to have:

- Aragon v0.5 screenshot in the blank screen.
- Thumbnail of the video and on click it blacks out the screen and starts playing

🙏

Discuss @jounih @bpierre @luisivan

**Comment by luisivan** [comment]
I can take this
