### ISSUE TITLE
Fix link to "try Aragon core 0.5"

### ISSUE THREAD

**Issue by uniconstructor** [aragon/website#64]
Use new url: https://aragon.aragonpm.com instead of https://app.aragon.one/
If you create a DAO using old url - the created DAO page will be broken.

See related issue: https://github.com/aragon/aragon/issues/314

**Comment by izqui** [comment]
The current link on the website is properly redirecting me to 
http://aragon.aragonpm.com/#/. What browser are you using?

**Comment by uniconstructor** [comment]
Anyway the http://rinkeby.aragon.network/ still returns an error - is this OK?

**Comment by john-light** [comment]
@uniconstructor where did you find the http://rinkeby.aragon.network/ link? We have never directed users to that URL afaik.

**Comment by luisivan** [comment]
Closing since we released a totally new version of the website
