### ISSUE TITLE
Footer is misaligned on mobile

### ISSUE THREAD

**Issue by john-light** [aragon/website#67]
See screenshots. The first screenshot shows the footer when scrolled all the way to the left, and you can see part of the first column is cut off. The second screenshot shows how one of the social icons is extending into white space that shouldn't be there.

![screenshot_20180831-111340_firefox](https://user-images.githubusercontent.com/9424721/45001206-12bf4600-af80-11e8-8d9b-e06b5e763386.jpg)
![screenshot_20180831-111403_firefox](https://user-images.githubusercontent.com/9424721/45001207-12bf4600-af80-11e8-82dc-535876078e8d.jpg)

**Comment by luisivan** [comment]
Closing since we released a totally new version of the website
