### ISSUE TITLE
/project: Add Stefano as the Executive Director

### ISSUE THREAD

**Issue by izqui** [aragon/website#80]
<img width="1172" alt="2019-01-10 at 7 32 00 pm" src="https://user-images.githubusercontent.com/447328/50988970-6c2b1900-150e-11e9-8907-c6e29695c95f.png">

**Executive Director** could appear as an item of the size of 'Board of Directors' and 'Stefano Bernardi' with the same weight as my name and Luis' have.

**Comment by izqui** [comment]
cc @luisivan

**Comment by luisivan** [comment]
Yes, let's do that
