### ISSUE TITLE
Alignment issue

### ISSUE THREAD

**Issue by GustavMarwin** [aragon/website#82]
I'm using the latest version of Brave (0.59.34) and this is how the project page is displayed for me (below). It seems the top banner regarding the AGP-1 vote is causing the icons/links to the different categories within the project section, to be "too high up"? It might seem like I haven't scrolled up enough, but I can assure you, I've scrolled as much as I could.

<img width="969" alt="screenshot 2019-02-03 at 15 32 30" src="https://user-images.githubusercontent.com/37633593/52178055-d5c6dc00-27c9-11e9-8c91-7f1caa15a65d.png">

**Comment by delfipolito** [comment]
Thanks!
